import type { Lang } from './i18n';

type Link = (key: 'lab' | 'trattoria-1978' | 'to-go' | 'la-cantina' | 'al-bargello', text: string) => string;
type Day = 'Mo' | 'Tu' | 'We' | 'Th' | 'Fr' | 'Sa' | 'Su';

const it = {
  meta: {
    homeTitle: 'Boboli — Scegli · Ristoranti 100% senza glutine a Firenze, dal 1978',
    homeDesc:
      'Boboli a Firenze: quattro locali e un laboratorio, tutta la cucina senza glutine. Trattoria, Bargello, To-Go e Cantina in Via Romana e Via Ghibellina. Prenota online.',
    placeTitle: (name: string, street: string) => `${name} — ristorante senza glutine a Firenze · ${street}`,
    placeDesc: (legal: string, blurb: string, addr: string, zone: string) =>
      `${legal}: ${blurb} ${addr}, ${zone}, Firenze. Tutto il menu è senza glutine.`,
    skip: 'Vai al contenuto',
    orgDesc:
      'Gruppo di ristorazione fiorentino con quattro locali e un laboratorio di produzione proprio: tutta la cucina è senza glutine.',
    cuisine: ['Toscana', 'Italiana'],
    menuName: 'Tutto il menu, senza glutine',
  },
  nav: {
    home: 'Trattoria Boboli, home',
    book: 'Prenota',
    open: 'Apri il menu',
    close: 'Chiudi il menu',
    menu: 'Menu',
    menuMeta: 'Tutto senza glutine',
    lab: 'Il laboratorio',
    labMeta: 'Fatto da noi',
    tagline: '100% gluten free · dal 1978 · Firenze',
  },
  hero: {
    word: 'Scegli',
    h1Hidden: 'cucina 100% senza glutine a Firenze',
    choices: ['la pasta.', 'il pane.', 'il panino.', 'pranzo o cena.', 'dove sederti.', 'con chi venire.'],
    choicesLabel: 'Cosa scegli da Boboli',
    answer: 'Tutto senza glutine.',
    since: 'Firenze, dal 1978.',
    alt: 'Una cuoca di Boboli stende a mano la pasta fresca senza glutine nel laboratorio',
  },
  choices: {
    title: 'Da Boboli la libertà di scegliere non riguarda solo il piatto.',
    homeVerb: 'Porta Boboli a casa',
    homeWhere: 'I prodotti del laboratorio',
  },
  format: { more: 'Il locale' },
  manifesto: {
    kicker: '100% gluten free',
    line1: 'Non scegli cosa puoi mangiare.',
    line2: 'Scegli cosa vuoi mangiare.',
    body: "Il senza glutine è il punto di partenza della cucina, non un'alternativa nel menu. Alla base resta la tradizione toscana: ricette tramandate, che continuano a vivere nella Boboli di oggi.",
    items: ['Pasta', 'Pane', 'Panini', 'Sughi', 'Dolci', 'Carne'],
    listLabel: 'Quello che trovi in tavola',
  },
  lab: {
    kicker: 'Il laboratorio',
    title: 'Fatto da noi.',
    thin: 'Controlliamo il prodotto dalla produzione fino al piatto.',
    text: 'Pasta, pane, panini, sughi e dolci nascono nel nostro laboratorio e arrivano nei quattro locali. Non è un reparto in più: è la prova concreta che tutto il menu può essere senza glutine senza rinunciare a niente.',
    alt: 'Il laboratorio di Boboli: la pasta fresca preparata a mano',
  },
  menu: {
    title: 'Cosa pensavi di non poter più mangiare?',
    items: [
      ['Pane', 'Dal nostro laboratorio, in tavola ogni giorno.'],
      ['Pasta fresca', 'Fatta da noi, con i sughi della tradizione.'],
      ['Panini', 'Anche da portare via, da Boboli To-Go.'],
      ['Sughi', 'Ricette toscane, preparate nel laboratorio.'],
      ['Dolci', 'Tutti senza glutine, tutti fatti da noi.'],
      ['Carne', 'La tradizione toscana, in tavola.'],
    ],
    gallery: {
      antipasti: ['Antipasti', 'Tagliere toscano con bruschette, salumi, olive e formaggio, tutto senza glutine'],
      pasta: ['Pasta', 'Tagliatelle al ragù senza glutine, fatte nel laboratorio Boboli'],
      carne: ['Carne', 'Bistecca alla fiorentina con un bicchiere di vino rosso'],
      dolci: ['Dolci', 'Tiramisù senza glutine di Boboli'],
    },
    shopStrong: 'Porta Boboli a casa.',
    shopText: 'Pasta, sughi e pane del laboratorio si comprano nei locali. Lo shop online arriva.',
  },
  locations: {
    title: 'Tre porte in Via Romana. Una in Via Ghibellina.',
    mapLabel: 'Mappa dei quattro locali Boboli a Firenze',
    directions: 'Indicazioni',
    landmarks: { duomo: 'Duomo', ponte: 'Ponte Vecchio', pitti: 'Palazzo Pitti', boboli: 'Giardino di Boboli', croce: 'Santa Croce' },
    firenzeCaption: 'A pochi passi dal Giardino di Boboli.',
    firenzeAlt: 'Veduta di Firenze dal Giardino di Boboli: il Duomo e i tetti della città',
  },
  seo: {
    title: 'Boboli a Firenze: cucina 100% gluten free, dal 1978',
    copy: (a: Link) => [
      `Boboli è un gruppo di ristorazione fiorentino con quattro locali e un laboratorio di produzione proprio. Tutta la cucina è senza glutine: non un menu alternativo accanto a quello normale, ma il punto di partenza di ogni piatto. Pasta fresca, pane, panini, sughi e dolci nascono nel ${a('lab', 'laboratorio')} e arrivano in tavola nei tre indirizzi di Via Romana, nell'Oltrarno — la ${a('trattoria-1978', 'Trattoria')} al 45/R, ${a('to-go', 'Boboli To-Go')} al 52, ${a('la-cantina', 'La Cantina')} al 60R — e al ${a('al-bargello', 'Bargello')} di Via Ghibellina 147/r, a Santa Croce.`,
      'La cucina è quella toscana, con le ricette legate alla storia della trattoria. Chi cerca un ristorante gluten free a Firenze — celiaco o no — per una famiglia, una coppia o un gruppo di amici trova un posto dove nessuno deve chiedere cosa può mangiare.',
    ],
    faqTitle: 'Domande che ci fanno spesso',
    faq: [
      ['Tutto il menu è senza glutine?', 'Sì, in tutti e quattro i locali. Il senza glutine è il punto di partenza della cucina: pasta, pane, panini, sughi e dolci nascono nel nostro laboratorio.'],
      ['Dove mangiare gluten free a Firenze?', 'In Oltrarno alla Trattoria di Via Romana 45/R, da Boboli To-Go al 52 e alla Cantina al 60R; a Santa Croce al Bargello, in Via Ghibellina 147/r.'],
      ['Serve prenotare?', 'È consigliato, soprattutto a cena e nel fine settimana. Trattoria, Bargello e Cantina si prenotano online dal pulsante Prenota; ogni locale risponde anche al telefono.'],
      ['Fate asporto e prodotti da portare a casa?', "Sì: Boboli To-Go in Via Romana 52 è il locale per l'asporto, e i prodotti del laboratorio — pasta, sughi, pane — si comprano nei locali."],
    ] as [string, string][],
    hoursQ: 'Che orari fanno i locali?',
  },
  book: {
    title: 'Dove vuoi prenotare?',
    sub: 'Quattro locali, tutto il menu senza glutine in ognuno.',
    book: 'Prenota',
    call: 'Chiama',
    back: 'Tutti i locali',
    close: 'Chiudi',
    widget: (name: string) => `Prenota da ${name}`,
  },
  footer: {
    tagline: ['La libertà di scegliere.', '100% gluten free · Firenze, dal 1978'],
    locali: 'I locali',
    discover: 'Scopri',
    links: { lab: 'Il laboratorio', manifesto: '100% gluten free', menu: 'Il menu', shop: 'I prodotti' },
    contact: 'Contatti',
    faq: 'Domande frequenti',
  },
  place: {
    crumb: 'Percorso',
    address: 'Indirizzo',
    phone: 'Telefono',
    hours: 'Orari',
    cuisine: 'Cucina',
    cuisineValue: 'Toscana, 100% senza glutine',
    directions: 'Come arrivare',
    text: 'Tutto il menu è senza glutine: pasta, pane, panini, sughi e dolci arrivano dal nostro laboratorio.',
    others: 'Gli altri locali',
  },
  hours: {
    short: { Mo: 'Lun', Tu: 'Mar', We: 'Mer', Th: 'Gio', Fr: 'Ven', Sa: 'Sab', Su: 'Dom' } as Record<Day, string>,
    long: { Mo: 'lunedì', Tu: 'martedì', We: 'mercoledì', Th: 'giovedì', Fr: 'venerdì', Sa: 'sabato', Su: 'domenica' } as Record<Day, string>,
    everyday: 'Tutti i giorni',
    closed: (days: string) => `Chiuso il ${days}`,
    time: (t: string) => t.replace(/^0/, '').replace(/:00$/, ''),
  },
};

export type Dict = typeof it;

const full = (t: string) => t.replace(/^0/, '');

const en: Dict = {
  meta: {
    homeTitle: 'Boboli — Gluten-free restaurants in Florence since 1978',
    homeDesc:
      'Boboli in Florence: four restaurants and our own workshop, the whole kitchen 100% gluten free. Trattoria, Bargello, To-Go and Cantina on Via Romana and Via Ghibellina. Book online.',
    placeTitle: (name, street) => `${name} — gluten-free restaurant in Florence · ${street}`,
    placeDesc: (legal, blurb, addr, zone) => `${legal}: ${blurb} ${addr}, ${zone}, Florence. The whole menu is gluten free.`,
    skip: 'Skip to content',
    orgDesc: 'Florentine restaurant group with four restaurants and its own production workshop: the whole kitchen is gluten free.',
    cuisine: ['Tuscan', 'Italian'],
    menuName: 'The whole menu, gluten free',
  },
  nav: {
    home: 'Trattoria Boboli, home',
    book: 'Book',
    open: 'Open menu',
    close: 'Close menu',
    menu: 'Menu',
    menuMeta: 'All gluten free',
    lab: 'The workshop',
    labMeta: 'Made by us',
    tagline: '100% gluten free · since 1978 · Florence',
  },
  hero: {
    word: 'Choose',
    h1Hidden: 'a 100% gluten-free kitchen in Florence',
    choices: ['the pasta.', 'the bread.', 'the sandwich.', 'lunch or dinner.', 'where to sit.', 'who to bring.'],
    choicesLabel: 'What you choose at Boboli',
    answer: 'All gluten free.',
    since: 'Florence, since 1978.',
    alt: 'A Boboli cook rolling out fresh gluten-free pasta by hand in the workshop',
  },
  choices: {
    title: "At Boboli, the freedom to choose isn't only about the dish.",
    homeVerb: 'Take Boboli home',
    homeWhere: 'Products from the workshop',
  },
  format: { more: 'The restaurant' },
  manifesto: {
    kicker: '100% gluten free',
    line1: "You don't choose what you can eat.",
    line2: 'You choose what you want to eat.',
    body: "Gluten free is where our kitchen starts, not an alternative on the menu. At its heart is Tuscan tradition: recipes handed down, still alive in today's Boboli.",
    items: ['Pasta', 'Bread', 'Sandwiches', 'Sauces', 'Desserts', 'Meat'],
    listLabel: "What you'll find on the table",
  },
  lab: {
    kicker: 'The workshop',
    title: 'Made by us.',
    thin: 'We follow every product from production to plate.',
    text: "Pasta, bread, sandwiches, sauces and desserts are made in our own workshop and go out to all four restaurants. It isn't an extra department: it's the proof that a whole menu can be gluten free without giving anything up.",
    alt: "Boboli's workshop: fresh pasta made by hand",
  },
  menu: {
    title: 'What did you think you could never eat again?',
    items: [
      ['Bread', 'From our workshop, on the table every day.'],
      ['Fresh pasta', 'Made by us, with traditional sauces.'],
      ['Sandwiches', 'To take away too, at Boboli To-Go.'],
      ['Sauces', 'Tuscan recipes, made in the workshop.'],
      ['Desserts', 'All gluten free, all made by us.'],
      ['Meat', 'Tuscan tradition, at the table.'],
    ],
    gallery: {
      antipasti: ['Starters', 'Tuscan board with bruschetta, cured meats, olives and cheese, all gluten free'],
      pasta: ['Pasta', 'Gluten-free tagliatelle with ragù, made in the Boboli workshop'],
      carne: ['Meat', 'Florentine T-bone steak with a glass of red wine'],
      dolci: ['Desserts', "Boboli's gluten-free tiramisù"],
    },
    shopStrong: 'Take Boboli home.',
    shopText: 'Pasta, sauces and bread from the workshop are sold in our restaurants. The online shop is on its way.',
  },
  locations: {
    title: 'Three doors on Via Romana. One on Via Ghibellina.',
    mapLabel: 'Map of the four Boboli restaurants in Florence',
    directions: 'Get directions',
    landmarks: { duomo: 'Duomo', ponte: 'Ponte Vecchio', pitti: 'Pitti Palace', boboli: 'Boboli Gardens', croce: 'Santa Croce' },
    firenzeCaption: 'A few steps from the Boboli Gardens.',
    firenzeAlt: 'Florence seen from the Boboli Gardens: the Duomo and the city rooftops',
  },
  seo: {
    title: 'Boboli in Florence: 100% gluten-free cooking since 1978',
    copy: (a) => [
      `Boboli is a Florentine restaurant group with four restaurants and its own production workshop. The whole kitchen is gluten free: not an alternative menu next to the regular one, but the starting point of every dish. Fresh pasta, bread, sandwiches, sauces and desserts are made in our ${a('lab', 'workshop')} and served at three addresses on Via Romana, in the Oltrarno — the ${a('trattoria-1978', 'Trattoria')} at 45/R, ${a('to-go', 'Boboli To-Go')} at 52, ${a('la-cantina', 'La Cantina')} at 60R — and at the ${a('al-bargello', 'Bargello')} on Via Ghibellina 147/r, in Santa Croce.`,
      'The cooking is Tuscan, with recipes rooted in the history of the trattoria. If you are looking for a gluten-free restaurant in Florence — coeliac or not — for a family, a couple or a group of friends, this is a place where nobody has to ask what they can eat.',
    ],
    faqTitle: 'Questions we often get',
    faq: [
      ['Is the whole menu gluten free?', 'Yes, at all four restaurants. Gluten free is where our cooking starts: pasta, bread, sandwiches, sauces and desserts are all made in our own workshop.'],
      ['Where can I eat gluten free in Florence?', 'In the Oltrarno at the Trattoria on Via Romana 45/R, at Boboli To-Go at number 52 and at the Cantina at 60R; in Santa Croce at the Bargello, Via Ghibellina 147/r.'],
      ['Do I need to book?', 'It is recommended, especially for dinner and at weekends. You can book the Trattoria, the Bargello and the Cantina online with the Book button, or call any of the restaurants.'],
      ['Do you do takeaway and products to take home?', 'Yes: Boboli To-Go on Via Romana 52 is our takeaway spot, and products from the workshop — pasta, sauces, bread — are sold in the restaurants.'],
    ],
    hoursQ: 'What are the opening hours?',
  },
  book: {
    title: 'Where would you like to book?',
    sub: 'Four restaurants, the whole menu gluten free in each.',
    book: 'Book',
    call: 'Call',
    back: 'All restaurants',
    close: 'Close',
    widget: (name) => `Book at ${name}`,
  },
  footer: {
    tagline: ['The freedom to choose.', '100% gluten free · Florence, since 1978'],
    locali: 'Our restaurants',
    discover: 'Discover',
    links: { lab: 'The workshop', manifesto: '100% gluten free', menu: 'The menu', shop: 'Products' },
    contact: 'Contact',
    faq: 'FAQ',
  },
  place: {
    crumb: 'Breadcrumb',
    address: 'Address',
    phone: 'Phone',
    hours: 'Opening hours',
    cuisine: 'Cuisine',
    cuisineValue: 'Tuscan, 100% gluten free',
    directions: 'Get directions',
    text: 'The whole menu is gluten free: pasta, bread, sandwiches, sauces and desserts come from our own workshop.',
    others: 'Our other restaurants',
  },
  hours: {
    short: { Mo: 'Mon', Tu: 'Tue', We: 'Wed', Th: 'Thu', Fr: 'Fri', Sa: 'Sat', Su: 'Sun' },
    long: { Mo: 'Monday', Tu: 'Tuesday', We: 'Wednesday', Th: 'Thursday', Fr: 'Friday', Sa: 'Saturday', Su: 'Sunday' },
    everyday: 'Every day',
    closed: (days) => `Closed on ${days}`,
    time: full,
  },
};

const es: Dict = {
  meta: {
    homeTitle: 'Boboli — Restaurantes sin gluten en Florencia desde 1978',
    homeDesc:
      'Boboli en Florencia: cuatro locales y obrador propio, toda la cocina 100% sin gluten. Trattoria, Bargello, To-Go y Cantina en Via Romana y Via Ghibellina. Reserva online.',
    placeTitle: (name, street) => `${name} — restaurante sin gluten en Florencia · ${street}`,
    placeDesc: (legal, blurb, addr, zone) => `${legal}: ${blurb} ${addr}, ${zone}, Florencia. Toda la carta es sin gluten.`,
    skip: 'Ir al contenido',
    orgDesc: 'Grupo de restauración florentino con cuatro locales y obrador propio: toda la cocina es sin gluten.',
    cuisine: ['Toscana', 'Italiana'],
    menuName: 'Toda la carta, sin gluten',
  },
  nav: {
    home: 'Trattoria Boboli, inicio',
    book: 'Reservar',
    open: 'Abrir el menú',
    close: 'Cerrar el menú',
    menu: 'Carta',
    menuMeta: 'Todo sin gluten',
    lab: 'El obrador',
    labMeta: 'Hecho por nosotros',
    tagline: '100% sin gluten · desde 1978 · Florencia',
  },
  hero: {
    word: 'Elige',
    h1Hidden: 'cocina 100% sin gluten en Florencia',
    choices: ['la pasta.', 'el pan.', 'el bocadillo.', 'comida o cena.', 'dónde sentarte.', 'con quién venir.'],
    choicesLabel: 'Lo que eliges en Boboli',
    answer: 'Todo sin gluten.',
    since: 'Florencia, desde 1978.',
    alt: 'Una cocinera de Boboli estira a mano pasta fresca sin gluten en el obrador',
  },
  choices: {
    title: 'En Boboli, la libertad de elegir no es solo cosa del plato.',
    homeVerb: 'Llévate Boboli a casa',
    homeWhere: 'Los productos del obrador',
  },
  format: { more: 'El local' },
  manifesto: {
    kicker: '100% sin gluten',
    line1: 'No eliges lo que puedes comer.',
    line2: 'Eliges lo que quieres comer.',
    body: 'El sin gluten es el punto de partida de la cocina, no una alternativa en la carta. En la base sigue la tradición toscana: recetas transmitidas que siguen vivas en la Boboli de hoy.',
    items: ['Pasta', 'Pan', 'Bocadillos', 'Salsas', 'Postres', 'Carne'],
    listLabel: 'Lo que encuentras en la mesa',
  },
  lab: {
    kicker: 'El obrador',
    title: 'Hecho por nosotros.',
    thin: 'Controlamos el producto desde la producción hasta el plato.',
    text: 'Pasta, pan, bocadillos, salsas y postres nacen en nuestro obrador y llegan a los cuatro locales. No es un departamento más: es la prueba de que toda una carta puede ser sin gluten sin renunciar a nada.',
    alt: 'El obrador de Boboli: pasta fresca hecha a mano',
  },
  menu: {
    title: '¿Qué creías que ya no podrías volver a comer?',
    items: [
      ['Pan', 'De nuestro obrador, en la mesa cada día.'],
      ['Pasta fresca', 'Hecha por nosotros, con las salsas de siempre.'],
      ['Bocadillos', 'También para llevar, en Boboli To-Go.'],
      ['Salsas', 'Recetas toscanas, preparadas en el obrador.'],
      ['Postres', 'Todos sin gluten, todos hechos por nosotros.'],
      ['Carne', 'La tradición toscana, en la mesa.'],
    ],
    gallery: {
      antipasti: ['Entrantes', 'Tabla toscana con bruschettas, embutidos, aceitunas y queso, todo sin gluten'],
      pasta: ['Pasta', 'Tagliatelle al ragù sin gluten, hechas en el obrador de Boboli'],
      carne: ['Carne', 'Bistecca alla fiorentina con una copa de vino tinto'],
      dolci: ['Postres', 'Tiramisú sin gluten de Boboli'],
    },
    shopStrong: 'Llévate Boboli a casa.',
    shopText: 'La pasta, las salsas y el pan del obrador se venden en los locales. La tienda online está en camino.',
  },
  locations: {
    title: 'Tres puertas en Via Romana. Una en Via Ghibellina.',
    mapLabel: 'Mapa de los cuatro locales Boboli en Florencia',
    directions: 'Cómo llegar',
    landmarks: { duomo: 'Duomo', ponte: 'Ponte Vecchio', pitti: 'Palacio Pitti', boboli: 'Jardín de Bóboli', croce: 'Santa Croce' },
    firenzeCaption: 'A pocos pasos del Jardín de Bóboli.',
    firenzeAlt: 'Florencia vista desde el Jardín de Bóboli: el Duomo y los tejados de la ciudad',
  },
  seo: {
    title: 'Boboli en Florencia: cocina 100% sin gluten desde 1978',
    copy: (a) => [
      `Boboli es un grupo de restauración florentino con cuatro locales y obrador propio. Toda la cocina es sin gluten: no una carta alternativa junto a la normal, sino el punto de partida de cada plato. Pasta fresca, pan, bocadillos, salsas y postres nacen en el ${a('lab', 'obrador')} y llegan a la mesa en tres direcciones de Via Romana, en el Oltrarno — la ${a('trattoria-1978', 'Trattoria')} en el 45/R, ${a('to-go', 'Boboli To-Go')} en el 52, ${a('la-cantina', 'La Cantina')} en el 60R — y en el ${a('al-bargello', 'Bargello')} de Via Ghibellina 147/r, en Santa Croce.`,
      'La cocina es toscana, con recetas ligadas a la historia de la trattoria. Si buscas un restaurante sin gluten en Florencia — seas celíaco o no — para ir en familia, en pareja o con amigos, aquí nadie tiene que preguntar qué puede comer.',
    ],
    faqTitle: 'Preguntas frecuentes',
    faq: [
      ['¿Toda la carta es sin gluten?', 'Sí, en los cuatro locales. El sin gluten es el punto de partida de la cocina: pasta, pan, bocadillos, salsas y postres nacen en nuestro obrador.'],
      ['¿Dónde comer sin gluten en Florencia?', 'En el Oltrarno, en la Trattoria de Via Romana 45/R, en Boboli To-Go en el 52 y en la Cantina en el 60R; en Santa Croce, en el Bargello, Via Ghibellina 147/r.'],
      ['¿Hace falta reservar?', 'Es recomendable, sobre todo para cenar y los fines de semana. La Trattoria, el Bargello y la Cantina se reservan online con el botón Reservar; también puedes llamar a cualquier local.'],
      ['¿Tenéis comida para llevar y productos para casa?', 'Sí: Boboli To-Go en Via Romana 52 es nuestro local para llevar, y los productos del obrador — pasta, salsas, pan — se venden en los locales.'],
    ],
    hoursQ: '¿Qué horarios tienen los locales?',
  },
  book: {
    title: '¿Dónde quieres reservar?',
    sub: 'Cuatro locales, toda la carta sin gluten en cada uno.',
    book: 'Reservar',
    call: 'Llamar',
    back: 'Todos los locales',
    close: 'Cerrar',
    widget: (name) => `Reservar en ${name}`,
  },
  footer: {
    tagline: ['La libertad de elegir.', '100% sin gluten · Florencia, desde 1978'],
    locali: 'Los locales',
    discover: 'Descubre',
    links: { lab: 'El obrador', manifesto: '100% sin gluten', menu: 'La carta', shop: 'Los productos' },
    contact: 'Contacto',
    faq: 'Preguntas frecuentes',
  },
  place: {
    crumb: 'Ruta de navegación',
    address: 'Dirección',
    phone: 'Teléfono',
    hours: 'Horario',
    cuisine: 'Cocina',
    cuisineValue: 'Toscana, 100% sin gluten',
    directions: 'Cómo llegar',
    text: 'Toda la carta es sin gluten: pasta, pan, bocadillos, salsas y postres llegan de nuestro obrador.',
    others: 'Los otros locales',
  },
  hours: {
    short: { Mo: 'Lun', Tu: 'Mar', We: 'Mié', Th: 'Jue', Fr: 'Vie', Sa: 'Sáb', Su: 'Dom' },
    long: { Mo: 'lunes', Tu: 'martes', We: 'miércoles', Th: 'jueves', Fr: 'viernes', Sa: 'sábado', Su: 'domingo' },
    everyday: 'Todos los días',
    closed: (days) => `Cerrado los ${days}`,
    time: full,
  },
};

const de: Dict = {
  meta: {
    homeTitle: 'Boboli — Glutenfreie Restaurants in Florenz seit 1978',
    homeDesc:
      'Boboli in Florenz: vier Restaurants und eine eigene Manufaktur, die ganze Küche 100 % glutenfrei. Trattoria, Bargello, To-Go und Cantina in der Via Romana und Via Ghibellina. Online reservieren.',
    placeTitle: (name, street) => `${name} — glutenfreies Restaurant in Florenz · ${street}`,
    placeDesc: (legal, blurb, addr, zone) => `${legal}: ${blurb} ${addr}, ${zone}, Florenz. Die ganze Karte ist glutenfrei.`,
    skip: 'Zum Inhalt',
    orgDesc: 'Florentiner Gastronomiegruppe mit vier Restaurants und eigener Manufaktur: die ganze Küche ist glutenfrei.',
    cuisine: ['Toskanisch', 'Italienisch'],
    menuName: 'Die ganze Karte, glutenfrei',
  },
  nav: {
    home: 'Trattoria Boboli, Startseite',
    book: 'Reservieren',
    open: 'Menü öffnen',
    close: 'Menü schließen',
    menu: 'Speisekarte',
    menuMeta: 'Alles glutenfrei',
    lab: 'Die Manufaktur',
    labMeta: 'Von uns gemacht',
    tagline: '100 % glutenfrei · seit 1978 · Florenz',
  },
  hero: {
    word: 'Wähle',
    h1Hidden: '100 % glutenfreie Küche in Florenz',
    choices: ['die Pasta.', 'das Brot.', 'das Panino.', 'Mittag oder Abend.', 'deinen Platz.', 'deine Begleitung.'],
    choicesLabel: 'Was du bei Boboli wählst',
    answer: 'Alles glutenfrei.',
    since: 'Florenz, seit 1978.',
    alt: 'Eine Köchin von Boboli rollt in der Manufaktur frische glutenfreie Pasta von Hand aus',
  },
  choices: {
    title: 'Bei Boboli geht die Freiheit der Wahl über den Teller hinaus.',
    homeVerb: 'Nimm Boboli mit nach Hause',
    homeWhere: 'Produkte aus der Manufaktur',
  },
  format: { more: 'Das Restaurant' },
  manifesto: {
    kicker: '100 % glutenfrei',
    line1: 'Du wählst nicht, was du essen darfst.',
    line2: 'Du wählst, was du essen willst.',
    body: 'Glutenfrei ist der Ausgangspunkt unserer Küche, keine Alternative auf der Karte. Im Kern steht die toskanische Tradition: überlieferte Rezepte, die im Boboli von heute weiterleben.',
    items: ['Pasta', 'Brot', 'Panini', 'Saucen', 'Desserts', 'Fleisch'],
    listLabel: 'Was auf den Tisch kommt',
  },
  lab: {
    kicker: 'Die Manufaktur',
    title: 'Von uns gemacht.',
    thin: 'Wir begleiten jedes Produkt von der Herstellung bis auf den Teller.',
    text: 'Pasta, Brot, Panini, Saucen und Desserts entstehen in unserer eigenen Manufaktur und gehen in alle vier Restaurants. Keine Abteilung mehr, sondern der Beweis, dass eine ganze Karte glutenfrei sein kann, ohne auf etwas zu verzichten.',
    alt: 'Die Manufaktur von Boboli: frische Pasta von Hand gemacht',
  },
  menu: {
    title: 'Was dachtest du, nie wieder essen zu können?',
    items: [
      ['Brot', 'Aus unserer Manufaktur, jeden Tag auf dem Tisch.'],
      ['Frische Pasta', 'Von uns gemacht, mit den klassischen Saucen.'],
      ['Panini', 'Auch zum Mitnehmen, bei Boboli To-Go.'],
      ['Saucen', 'Toskanische Rezepte, in der Manufaktur zubereitet.'],
      ['Desserts', 'Alle glutenfrei, alle von uns gemacht.'],
      ['Fleisch', 'Toskanische Tradition auf dem Tisch.'],
    ],
    gallery: {
      antipasti: ['Antipasti', 'Toskanisches Brett mit Bruschetta, Wurst, Oliven und Käse, alles glutenfrei'],
      pasta: ['Pasta', 'Glutenfreie Tagliatelle mit Ragù aus der Boboli-Manufaktur'],
      carne: ['Fleisch', 'Bistecca alla fiorentina mit einem Glas Rotwein'],
      dolci: ['Desserts', 'Glutenfreies Tiramisù von Boboli'],
    },
    shopStrong: 'Nimm Boboli mit nach Hause.',
    shopText: 'Pasta, Saucen und Brot aus der Manufaktur gibt es in unseren Restaurants. Der Onlineshop kommt bald.',
  },
  locations: {
    title: 'Drei Türen in der Via Romana. Eine in der Via Ghibellina.',
    mapLabel: 'Karte der vier Boboli-Restaurants in Florenz',
    directions: 'Route',
    landmarks: { duomo: 'Dom', ponte: 'Ponte Vecchio', pitti: 'Palazzo Pitti', boboli: 'Boboli-Garten', croce: 'Santa Croce' },
    firenzeCaption: 'Wenige Schritte vom Boboli-Garten.',
    firenzeAlt: 'Florenz vom Boboli-Garten aus: der Dom und die Dächer der Stadt',
  },
  seo: {
    title: 'Boboli in Florenz: 100 % glutenfreie Küche seit 1978',
    copy: (a) => [
      `Boboli ist eine Florentiner Gastronomiegruppe mit vier Restaurants und eigener Manufaktur. Die ganze Küche ist glutenfrei: keine Alternativkarte neben der normalen, sondern der Ausgangspunkt jedes Gerichts. Frische Pasta, Brot, Panini, Saucen und Desserts entstehen in der ${a('lab', 'Manufaktur')} und kommen an drei Adressen in der Via Romana im Oltrarno auf den Tisch — in der ${a('trattoria-1978', 'Trattoria')} in Nr. 45/R, bei ${a('to-go', 'Boboli To-Go')} in Nr. 52, in ${a('la-cantina', 'La Cantina')} in Nr. 60R — und im ${a('al-bargello', 'Bargello')} in der Via Ghibellina 147/r, in Santa Croce.`,
      'Die Küche ist toskanisch, mit Rezepten aus der Geschichte der Trattoria. Wer ein glutenfreies Restaurant in Florenz sucht — ob mit Zöliakie oder ohne —, für die Familie, zu zweit oder mit Freunden, findet hier einen Ort, an dem niemand fragen muss, was er essen darf.',
    ],
    faqTitle: 'Häufige Fragen',
    faq: [
      ['Ist die ganze Karte glutenfrei?', 'Ja, in allen vier Restaurants. Glutenfrei ist der Ausgangspunkt unserer Küche: Pasta, Brot, Panini, Saucen und Desserts entstehen in unserer eigenen Manufaktur.'],
      ['Wo kann man in Florenz glutenfrei essen?', 'Im Oltrarno in der Trattoria in der Via Romana 45/R, bei Boboli To-Go in Nr. 52 und in der Cantina in Nr. 60R; in Santa Croce im Bargello, Via Ghibellina 147/r.'],
      ['Muss ich reservieren?', 'Empfehlenswert, vor allem abends und am Wochenende. Trattoria, Bargello und Cantina reservierst du online über den Button Reservieren; jedes Restaurant ist auch telefonisch erreichbar.'],
      ['Gibt es Essen zum Mitnehmen und Produkte für zu Hause?', 'Ja: Boboli To-Go in der Via Romana 52 ist unser Take-away, und die Produkte der Manufaktur — Pasta, Saucen, Brot — gibt es in den Restaurants.'],
    ],
    hoursQ: 'Wann haben die Restaurants geöffnet?',
  },
  book: {
    title: 'Wo möchtest du reservieren?',
    sub: 'Vier Restaurants, in jedem die ganze Karte glutenfrei.',
    book: 'Reservieren',
    call: 'Anrufen',
    back: 'Alle Restaurants',
    close: 'Schließen',
    widget: (name) => `Reservieren bei ${name}`,
  },
  footer: {
    tagline: ['Die Freiheit zu wählen.', '100 % glutenfrei · Florenz, seit 1978'],
    locali: 'Unsere Restaurants',
    discover: 'Entdecken',
    links: { lab: 'Die Manufaktur', manifesto: '100 % glutenfrei', menu: 'Die Speisekarte', shop: 'Produkte' },
    contact: 'Kontakt',
    faq: 'Häufige Fragen',
  },
  place: {
    crumb: 'Navigationspfad',
    address: 'Adresse',
    phone: 'Telefon',
    hours: 'Öffnungszeiten',
    cuisine: 'Küche',
    cuisineValue: 'Toskanisch, 100 % glutenfrei',
    directions: 'Route planen',
    text: 'Die ganze Karte ist glutenfrei: Pasta, Brot, Panini, Saucen und Desserts kommen aus unserer eigenen Manufaktur.',
    others: 'Unsere anderen Restaurants',
  },
  hours: {
    short: { Mo: 'Mo', Tu: 'Di', We: 'Mi', Th: 'Do', Fr: 'Fr', Sa: 'Sa', Su: 'So' },
    long: { Mo: 'Montag', Tu: 'Dienstag', We: 'Mittwoch', Th: 'Donnerstag', Fr: 'Freitag', Sa: 'Samstag', Su: 'Sonntag' },
    everyday: 'Täglich',
    closed: (days) => `${days} geschlossen`,
    time: full,
  },
};

const fr: Dict = {
  meta: {
    homeTitle: 'Boboli — Restaurants sans gluten à Florence depuis 1978',
    homeDesc:
      'Boboli à Florence : quatre adresses et notre propre atelier, toute la cuisine 100 % sans gluten. Trattoria, Bargello, To-Go et Cantina via Romana et via Ghibellina. Réservation en ligne.',
    placeTitle: (name, street) => `${name} — restaurant sans gluten à Florence · ${street}`,
    placeDesc: (legal, blurb, addr, zone) => `${legal} : ${blurb} ${addr}, ${zone}, Florence. Toute la carte est sans gluten.`,
    skip: 'Aller au contenu',
    orgDesc: 'Groupe de restauration florentin avec quatre adresses et son propre atelier de production : toute la cuisine est sans gluten.',
    cuisine: ['Toscane', 'Italienne'],
    menuName: 'Toute la carte, sans gluten',
  },
  nav: {
    home: 'Trattoria Boboli, accueil',
    book: 'Réserver',
    open: 'Ouvrir le menu',
    close: 'Fermer le menu',
    menu: 'La carte',
    menuMeta: 'Tout sans gluten',
    lab: "L'atelier",
    labMeta: 'Fait maison',
    tagline: '100 % sans gluten · depuis 1978 · Florence',
  },
  hero: {
    word: 'Choisis',
    h1Hidden: 'une cuisine 100 % sans gluten à Florence',
    choices: ['les pâtes.', 'le pain.', 'le sandwich.', 'déjeuner ou dîner.', 'où t’asseoir.', 'avec qui venir.'],
    choicesLabel: 'Ce que tu choisis chez Boboli',
    answer: 'Tout sans gluten.',
    since: 'Florence, depuis 1978.',
    alt: "Une cuisinière de Boboli étale à la main des pâtes fraîches sans gluten dans l'atelier",
  },
  choices: {
    title: "Chez Boboli, la liberté de choisir ne s'arrête pas à l'assiette.",
    homeVerb: 'Emporte Boboli chez toi',
    homeWhere: "Les produits de l'atelier",
  },
  format: { more: "L'adresse" },
  manifesto: {
    kicker: '100 % sans gluten',
    line1: 'Tu ne choisis pas ce que tu peux manger.',
    line2: 'Tu choisis ce que tu veux manger.',
    body: "Le sans gluten est le point de départ de notre cuisine, pas une alternative sur la carte. À la base, la tradition toscane : des recettes transmises, toujours vivantes dans le Boboli d'aujourd'hui.",
    items: ['Pâtes', 'Pain', 'Sandwichs', 'Sauces', 'Desserts', 'Viande'],
    listLabel: "Ce que tu trouves à table",
  },
  lab: {
    kicker: "L'atelier",
    title: 'Fait maison.',
    thin: "Nous suivons chaque produit, de la fabrication jusqu'à l'assiette.",
    text: "Pâtes, pain, sandwichs, sauces et desserts naissent dans notre atelier et partent vers nos quatre adresses. Ce n'est pas un service de plus : c'est la preuve qu'une carte entière peut être sans gluten sans renoncer à rien.",
    alt: "L'atelier de Boboli : des pâtes fraîches faites à la main",
  },
  menu: {
    title: 'Qu’est-ce que tu pensais ne plus jamais pouvoir manger ?',
    items: [
      ['Pain', 'De notre atelier, sur la table chaque jour.'],
      ['Pâtes fraîches', 'Faites par nous, avec les sauces de toujours.'],
      ['Sandwichs', 'Aussi à emporter, chez Boboli To-Go.'],
      ['Sauces', "Recettes toscanes, préparées à l'atelier."],
      ['Desserts', 'Tous sans gluten, tous faits maison.'],
      ['Viande', 'La tradition toscane, à table.'],
    ],
    gallery: {
      antipasti: ['Antipasti', 'Planche toscane avec bruschettas, charcuterie, olives et fromage, tout sans gluten'],
      pasta: ['Pâtes', "Tagliatelles au ragù sans gluten, faites à l'atelier Boboli"],
      carne: ['Viande', "Bistecca alla fiorentina avec un verre de vin rouge"],
      dolci: ['Desserts', 'Tiramisù sans gluten de Boboli'],
    },
    shopStrong: 'Emporte Boboli chez toi.',
    shopText: "Pâtes, sauces et pain de l'atelier sont en vente dans nos adresses. La boutique en ligne arrive.",
  },
  locations: {
    title: 'Trois portes via Romana. Une via Ghibellina.',
    mapLabel: 'Carte des quatre adresses Boboli à Florence',
    directions: 'Itinéraire',
    landmarks: { duomo: 'Duomo', ponte: 'Ponte Vecchio', pitti: 'Palais Pitti', boboli: 'Jardin de Boboli', croce: 'Santa Croce' },
    firenzeCaption: 'À quelques pas du jardin de Boboli.',
    firenzeAlt: 'Florence vue du jardin de Boboli : le Duomo et les toits de la ville',
  },
  seo: {
    title: 'Boboli à Florence : cuisine 100 % sans gluten depuis 1978',
    copy: (a) => [
      `Boboli est un groupe de restauration florentin avec quatre adresses et son propre atelier de production. Toute la cuisine est sans gluten : pas une carte alternative à côté de la carte normale, mais le point de départ de chaque plat. Pâtes fraîches, pain, sandwichs, sauces et desserts naissent dans l'${a('lab', 'atelier')} et arrivent à table à trois adresses de la via Romana, dans l'Oltrarno — la ${a('trattoria-1978', 'Trattoria')} au 45/R, ${a('to-go', 'Boboli To-Go')} au 52, ${a('la-cantina', 'La Cantina')} au 60R — et au ${a('al-bargello', 'Bargello')}, via Ghibellina 147/r, à Santa Croce.`,
      "La cuisine est toscane, avec des recettes liées à l'histoire de la trattoria. Si tu cherches un restaurant sans gluten à Florence — cœliaque ou non — en famille, en couple ou entre amis, c'est un endroit où personne n'a à demander ce qu'il peut manger.",
    ],
    faqTitle: 'Questions fréquentes',
    faq: [
      ['Toute la carte est-elle sans gluten ?', "Oui, dans nos quatre adresses. Le sans gluten est le point de départ de notre cuisine : pâtes, pain, sandwichs, sauces et desserts naissent dans notre atelier."],
      ['Où manger sans gluten à Florence ?', "Dans l'Oltrarno, à la Trattoria au 45/R de la via Romana, chez Boboli To-Go au 52 et à la Cantina au 60R ; à Santa Croce, au Bargello, via Ghibellina 147/r."],
      ['Faut-il réserver ?', "C'est conseillé, surtout le soir et le week-end. La Trattoria, le Bargello et la Cantina se réservent en ligne avec le bouton Réserver ; chaque adresse répond aussi au téléphone."],
      ['Faites-vous de la vente à emporter et des produits à rapporter ?', "Oui : Boboli To-Go, au 52 de la via Romana, est notre adresse à emporter, et les produits de l'atelier — pâtes, sauces, pain — sont en vente dans nos adresses."],
    ],
    hoursQ: "Quels sont les horaires d'ouverture ?",
  },
  book: {
    title: 'Où veux-tu réserver ?',
    sub: 'Quatre adresses, toute la carte sans gluten dans chacune.',
    book: 'Réserver',
    call: 'Appeler',
    back: 'Toutes les adresses',
    close: 'Fermer',
    widget: (name) => `Réserver chez ${name}`,
  },
  footer: {
    tagline: ['La liberté de choisir.', '100 % sans gluten · Florence, depuis 1978'],
    locali: 'Nos adresses',
    discover: 'Découvrir',
    links: { lab: "L'atelier", manifesto: '100 % sans gluten', menu: 'La carte', shop: 'Les produits' },
    contact: 'Contact',
    faq: 'Questions fréquentes',
  },
  place: {
    crumb: "Fil d'Ariane",
    address: 'Adresse',
    phone: 'Téléphone',
    hours: 'Horaires',
    cuisine: 'Cuisine',
    cuisineValue: 'Toscane, 100 % sans gluten',
    directions: 'Itinéraire',
    text: "Toute la carte est sans gluten : pâtes, pain, sandwichs, sauces et desserts viennent de notre atelier.",
    others: 'Nos autres adresses',
  },
  hours: {
    short: { Mo: 'Lun', Tu: 'Mar', We: 'Mer', Th: 'Jeu', Fr: 'Ven', Sa: 'Sam', Su: 'Dim' },
    long: { Mo: 'lundi', Tu: 'mardi', We: 'mercredi', Th: 'jeudi', Fr: 'vendredi', Sa: 'samedi', Su: 'dimanche' },
    everyday: 'Tous les jours',
    closed: (days) => `Fermé le ${days}`,
    time: (t) => t.replace(/^0/, '').replace(':', 'h').replace(/h00$/, 'h'),
  },
};

export const ui: Record<Lang, Dict> = { it, en, es, de, fr };
