import type { Lang } from './i18n';

type Link = (key: 'prodotti' | 'trattoria-1978' | 'to-go' | 'la-cantina' | 'al-bargello', text: string) => string;
type Day = 'Mo' | 'Tu' | 'We' | 'Th' | 'Fr' | 'Sa' | 'Su';

const it = {
  meta: {
    homeTitle: 'Boboli — Scegli · Ristoranti 100% senza glutine a Firenze, dal 1978',
    homeDesc:
      'Boboli a Firenze: quattro locali e un laboratorio, tutta la cucina senza glutine. Trattoria, Bargello, To-Go e Cantina in Via Romana e Via Ghibellina. Prenota online.',
    placeTitle: (name: string, street: string) => `${name} — ristorante senza glutine a Firenze · ${street}`,
    placeDesc: (legal: string, blurb: string, addr: string, zone: string) =>
      `${legal}: ${blurb} ${addr}, ${zone}, Firenze. Tutto il menu è senza glutine.`,
    skip: 'Vai al contenuto',
    orgDesc:
      'Gruppo di ristorazione fiorentino con quattro locali e un laboratorio di produzione proprio: tutta la cucina è senza glutine.',
    cuisine: ['Toscana', 'Italiana'],
    menuName: 'Tutto il menu, senza glutine',
  },
  nav: {
    home: 'Trattoria Boboli, home',
    book: 'Prenota',
    open: 'Apri il menu',
    close: 'Chiudi il menu',
    menu: 'Menu',
    menuMeta: 'Tutto senza glutine',
    lab: 'Il laboratorio',
    labMeta: 'Fatto da noi',
    tagline: '100% gluten free · dal 1978 · Firenze',
  },
  hero: {
    word: 'Scegli',
    h1Hidden: 'cucina 100% senza glutine a Firenze',
    choices: ['la pasta.', 'il panino.', 'pranzo o cena.', 'dove sederti.', 'con chi venire.', 'come vivere Boboli.'],
    choicesLabel: 'Cosa scegli da Boboli',
    answer: 'Tutto senza glutine.',
    since: 'Firenze, dal 1978.',
    alt: 'Una cuoca di Boboli stende a mano la pasta fresca senza glutine nel laboratorio',
  },
  choices: {
    title: 'Da Boboli scegli anche come stare a tavola.',
    homeVerb: 'Porta Boboli a casa',
    homeWhere: 'I prodotti del laboratorio',
    homeSub: 'Quella voglia di Boboli può continuare anche quando sei già rientrato.',
  },
  format: { more: 'Il locale' },
  manifesto: {
    kicker: '100% gluten free',
    title: 'Scegli quello che hai voglia di mangiare.',
    body: 'Una pasta fumante. Un panino appena fatto. Un dolce da dividere. Il pane da mettere al centro del tavolo. Da Boboli tutto è senza glutine, così a scegliere resta solo quello che ti va davvero.',
    items: ['Pasta', 'Pane', 'Panini', 'Sughi', 'Dolci', 'Carne'],
    listLabel: 'Quello che trovi in tavola',
  },
  lab: {
    kicker: 'Il laboratorio',
    title: 'Fatto da noi.',
    thin: 'Il pane lo facciamo noi. La pasta la facciamo noi. E anche quello che ci mettiamo dentro parte dalla nostra cucina.',
    text: [
      'Perché fare le cose in casa non è solo una questione di tradizione: è il modo che abbiamo scelto per sapere esattamente cosa arriva nel tuo piatto.',
      'Ogni giorno partiamo da ingredienti scelti con cura e da ricette che conosciamo bene. Così possiamo portare in tavola una cucina senza glutine che non ha bisogno di imitare niente.',
    ],
    alt: 'Il laboratorio di Boboli: la pasta fresca preparata a mano',
  },
  menu: {
    title: 'E tu, oggi, cosa hai voglia di mangiare?',
    items: ['Pane', 'Panini', 'Pasta fresca', 'Pasta', 'Sughi', 'Carne', 'Dolci'],
    note: 'La scelta è tua. Noi ci occupiamo di prepararla senza glutine.',
    gallery: {
      antipasti: ['Antipasti', 'Da mettere al centro e condividere.', 'Tagliere toscano con bruschette, salumi, olive e formaggio, tutto senza glutine'],
      pasta: ['Pasta', 'Quella che vorresti trovare nel piatto.', 'Tagliatelle al ragù senza glutine, fatte nel laboratorio Boboli'],
      carne: ['Carne', 'Per quando hai proprio fame.', 'Bistecca alla fiorentina con un bicchiere di vino rosso'],
      dolci: ['Dolci', 'Per chiudere come si deve.', 'Tiramisù senza glutine di Boboli'],
    },
    shopStrong: 'Porta Boboli a casa.',
    shopText: 'Pasta, sughi e pane del laboratorio si comprano nei locali. Lo shop online arriva.',
  },
  locations: {
    title: 'Quattro indirizzi, un solo modo di fare Boboli.',
    sub: 'Dalla trattoria alla cantina, dal panino da portare via alla cena al Bargello: scegli il posto che fa per te.',
    mapLabel: 'Mappa dei quattro locali Boboli a Firenze',
    directions: 'Indicazioni',
    landmarks: { duomo: 'Duomo', ponte: 'Ponte Vecchio', pitti: 'Palazzo Pitti', boboli: 'Giardino di Boboli', croce: 'Santa Croce' },
    firenzeCaption: 'Boboli è Firenze. E Firenze si mangia anche così.',
    firenzeAlt: 'Veduta di Firenze dal Giardino di Boboli: il Duomo e i tetti della città',
  },
  seo: {
    title: 'Boboli a Firenze: cucina 100% senza glutine dal 1978',
    copy: (a: Link) => [
      'Dal 1978 Boboli porta a Firenze una cucina pensata per essere condivisa, scelta e vissuta senza compromessi.',
      `Oggi puoi trovarci in Via Romana e in Via Ghibellina, per ${a('al-bargello', 'una cena')}, ${a('trattoria-1978', 'un pranzo in trattoria')}, ${a('la-cantina', 'un bicchiere in cantina')}, ${a('to-go', 'un panino da portare via')} o ${a('prodotti', 'qualcosa di buono da portare a casa')}.`,
      'La nostra cucina è 100% senza glutine, ma non è questo che vogliamo farti ricordare. Vogliamo che tu ricordi cosa hai mangiato, con chi eri e quanto ti sei goduto il momento.',
    ],
    faqTitle: 'Domande che ci fanno spesso',
    faq: [
      ['Tutto il menu è senza glutine?', 'Sì, in tutti e quattro i locali. Il senza glutine è il punto di partenza della cucina: pasta, pane, panini, sughi e dolci nascono nel nostro laboratorio.'],
      ['Dove mangiare gluten free a Firenze?', 'In Oltrarno alla Trattoria di Via Romana 45/R, da Boboli To-Go al 52 e alla Cantina al 60R; a Santa Croce al Bargello, in Via Ghibellina 147/r.'],
      ['Serve prenotare?', 'È consigliato, soprattutto a cena e nel fine settimana. Trattoria, Bargello e Cantina si prenotano online dal pulsante Prenota; ogni locale risponde anche al telefono.'],
      ['Fate asporto e prodotti da portare a casa?', "Sì: Boboli To-Go in Via Romana 52 è il locale per l'asporto, e i prodotti del laboratorio — pasta, sughi, pane — si comprano nei locali."],
    ] as [string, string][],
    hoursQ: 'Che orari fanno i locali?',
  },
  book: {
    title: 'Dove vuoi prenotare?',
    sub: 'Quattro locali, tutto il menu senza glutine in ognuno.',
    book: 'Prenota',
    call: 'Chiama',
    back: 'Tutti i locali',
    close: 'Chiudi',
    widget: (name: string) => `Prenota da ${name}`,
  },
  footer: {
    tagline: ['La libertà di scegliere.', '100% gluten free · Firenze, dal 1978'],
    locali: 'I locali',
    discover: 'Scopri',
    links: { lab: 'Il laboratorio', manifesto: '100% gluten free', menu: 'Il menu', shop: 'I prodotti' },
    contact: 'Contatti',
    faq: 'Domande frequenti',
  },
  place: {
    crumb: 'Percorso',
    address: 'Indirizzo',
    phone: 'Telefono',
    hours: 'Orari',
    cuisine: 'Cucina',
    cuisineValue: 'Toscana, 100% senza glutine',
    directions: 'Come arrivare',
    text: 'Tutto il menu è senza glutine: pasta, pane, panini, sughi e dolci arrivano dal nostro laboratorio.',
    others: 'Gli altri locali',
  },
  hours: {
    short: { Mo: 'Lun', Tu: 'Mar', We: 'Mer', Th: 'Gio', Fr: 'Ven', Sa: 'Sab', Su: 'Dom' } as Record<Day, string>,
    long: { Mo: 'lunedì', Tu: 'martedì', We: 'mercoledì', Th: 'giovedì', Fr: 'venerdì', Sa: 'sabato', Su: 'domenica' } as Record<Day, string>,
    everyday: 'Tutti i giorni',
    closed: (days: string) => `Chiuso il ${days}`,
    time: (t: string) => t.replace(/^0/, '').replace(/:00$/, ''),
  },
};

export type Dict = typeof it;

const full = (t: string) => t.replace(/^0/, '');

const en: Dict = {
  meta: {
    homeTitle: 'Boboli — Gluten-free restaurants in Florence since 1978',
    homeDesc:
      'Boboli in Florence: four restaurants and our own workshop, the whole kitchen 100% gluten free. Trattoria, Bargello, To-Go and Cantina on Via Romana and Via Ghibellina. Book online.',
    placeTitle: (name, street) => `${name} — gluten-free restaurant in Florence · ${street}`,
    placeDesc: (legal, blurb, addr, zone) => `${legal}: ${blurb} ${addr}, ${zone}, Florence. The whole menu is gluten free.`,
    skip: 'Skip to content',
    orgDesc: 'Florentine restaurant group with four restaurants and its own production workshop: the whole kitchen is gluten free.',
    cuisine: ['Tuscan', 'Italian'],
    menuName: 'The whole menu, gluten free',
  },
  nav: {
    home: 'Trattoria Boboli, home',
    book: 'Book',
    open: 'Open menu',
    close: 'Close menu',
    menu: 'Menu',
    menuMeta: 'All gluten free',
    lab: 'The workshop',
    labMeta: 'Made by us',
    tagline: '100% gluten free · since 1978 · Florence',
  },
  hero: {
    word: 'Choose',
    h1Hidden: 'a 100% gluten-free kitchen in Florence',
    choices: ['the pasta.', 'the sandwich.', 'lunch or dinner.', 'where to sit.', 'who to bring.', 'how to enjoy Boboli.'],
    choicesLabel: 'What you choose at Boboli',
    answer: 'All gluten free.',
    since: 'Florence, since 1978.',
    alt: 'A Boboli cook rolling out fresh gluten-free pasta by hand in the workshop',
  },
  choices: {
    title: 'At Boboli, you also choose how you spend time at the table.',
    homeVerb: 'Take Boboli home',
    homeWhere: 'Products from the workshop',
    homeSub: "That Boboli craving can carry on even once you're back home.",
  },
  format: { more: 'The restaurant' },
  manifesto: {
    kicker: '100% gluten free',
    title: 'Choose what you feel like eating.',
    body: "A steaming plate of pasta. A freshly made sandwich. A dessert to share. Bread for the middle of the table. At Boboli everything is gluten free, so all that's left to choose is what you really want.",
    items: ['Pasta', 'Bread', 'Sandwiches', 'Sauces', 'Desserts', 'Meat'],
    listLabel: "What you'll find on the table",
  },
  lab: {
    kicker: 'The workshop',
    title: 'Made by us.',
    thin: 'We make the bread. We make the pasta. And what goes into them starts in our own kitchen too.',
    text: [
      "Because making things in-house isn't just about tradition: it's how we've chosen to know exactly what reaches your plate.",
      "Every day we start from carefully chosen ingredients and recipes we know well. That's how we can serve gluten-free cooking that doesn't need to imitate anything.",
    ],
    alt: "Boboli's workshop: fresh pasta made by hand",
  },
  menu: {
    title: 'So, what do you feel like eating today?',
    items: ['Bread', 'Sandwiches', 'Fresh pasta', 'Pasta', 'Sauces', 'Meat', 'Desserts'],
    note: "The choice is yours. We'll take care of making it gluten free.",
    gallery: {
      antipasti: ['Starters', 'For the middle of the table, to share.', 'Tuscan board with bruschetta, cured meats, olives and cheese, all gluten free'],
      pasta: ['Pasta', 'The kind you hope to find on your plate.', 'Gluten-free tagliatelle with ragù, made in the Boboli workshop'],
      carne: ['Meat', "For when you're really hungry.", 'Florentine T-bone steak with a glass of red wine'],
      dolci: ['Desserts', 'The proper way to finish.', "Boboli's gluten-free tiramisù"],
    },
    shopStrong: 'Take Boboli home.',
    shopText: 'Pasta, sauces and bread from the workshop are sold in our restaurants. The online shop is on its way.',
  },
  locations: {
    title: 'Four addresses, one way of doing Boboli.',
    sub: 'From the trattoria to the cantina, from a sandwich to go to dinner at the Bargello: pick the place that suits you.',
    mapLabel: 'Map of the four Boboli restaurants in Florence',
    directions: 'Get directions',
    landmarks: { duomo: 'Duomo', ponte: 'Ponte Vecchio', pitti: 'Pitti Palace', boboli: 'Boboli Gardens', croce: 'Santa Croce' },
    firenzeCaption: 'Boboli is Florence. And Florence tastes like this, too.',
    firenzeAlt: 'Florence seen from the Boboli Gardens: the Duomo and the city rooftops',
  },
  seo: {
    title: 'Boboli in Florence: 100% gluten-free cooking since 1978',
    copy: (a) => [
      'Since 1978 Boboli has brought Florence a kind of cooking made to be shared, chosen and enjoyed without compromise.',
      `Today you'll find us on Via Romana and Via Ghibellina, for ${a('al-bargello', 'dinner')}, ${a('trattoria-1978', 'lunch at the trattoria')}, ${a('la-cantina', 'a glass at the cantina')}, ${a('to-go', 'a sandwich to go')} or ${a('prodotti', 'something good to take home')}.`,
      "Our cooking is 100% gluten free, but that's not what we want you to remember. We want you to remember what you ate, who you were with and how much you enjoyed the moment.",
    ],
    faqTitle: 'Questions we often get',
    faq: [
      ['Is the whole menu gluten free?', 'Yes, at all four restaurants. Gluten free is where our cooking starts: pasta, bread, sandwiches, sauces and desserts are all made in our own workshop.'],
      ['Where can I eat gluten free in Florence?', 'In the Oltrarno at the Trattoria on Via Romana 45/R, at Boboli To-Go at number 52 and at the Cantina at 60R; in Santa Croce at the Bargello, Via Ghibellina 147/r.'],
      ['Do I need to book?', 'It is recommended, especially for dinner and at weekends. You can book the Trattoria, the Bargello and the Cantina online with the Book button, or call any of the restaurants.'],
      ['Do you do takeaway and products to take home?', 'Yes: Boboli To-Go on Via Romana 52 is our takeaway spot, and products from the workshop — pasta, sauces, bread — are sold in the restaurants.'],
    ],
    hoursQ: 'What are the opening hours?',
  },
  book: {
    title: 'Where would you like to book?',
    sub: 'Four restaurants, the whole menu gluten free in each.',
    book: 'Book',
    call: 'Call',
    back: 'All restaurants',
    close: 'Close',
    widget: (name) => `Book at ${name}`,
  },
  footer: {
    tagline: ['The freedom to choose.', '100% gluten free · Florence, since 1978'],
    locali: 'Our restaurants',
    discover: 'Discover',
    links: { lab: 'The workshop', manifesto: '100% gluten free', menu: 'The menu', shop: 'Products' },
    contact: 'Contact',
    faq: 'FAQ',
  },
  place: {
    crumb: 'Breadcrumb',
    address: 'Address',
    phone: 'Phone',
    hours: 'Opening hours',
    cuisine: 'Cuisine',
    cuisineValue: 'Tuscan, 100% gluten free',
    directions: 'Get directions',
    text: 'The whole menu is gluten free: pasta, bread, sandwiches, sauces and desserts come from our own workshop.',
    others: 'Our other restaurants',
  },
  hours: {
    short: { Mo: 'Mon', Tu: 'Tue', We: 'Wed', Th: 'Thu', Fr: 'Fri', Sa: 'Sat', Su: 'Sun' },
    long: { Mo: 'Monday', Tu: 'Tuesday', We: 'Wednesday', Th: 'Thursday', Fr: 'Friday', Sa: 'Saturday', Su: 'Sunday' },
    everyday: 'Every day',
    closed: (days) => `Closed on ${days}`,
    time: full,
  },
};

const es: Dict = {
  meta: {
    homeTitle: 'Boboli — Restaurantes sin gluten en Florencia desde 1978',
    homeDesc:
      'Boboli en Florencia: cuatro locales y obrador propio, toda la cocina 100% sin gluten. Trattoria, Bargello, To-Go y Cantina en Via Romana y Via Ghibellina. Reserva online.',
    placeTitle: (name, street) => `${name} — restaurante sin gluten en Florencia · ${street}`,
    placeDesc: (legal, blurb, addr, zone) => `${legal}: ${blurb} ${addr}, ${zone}, Florencia. Toda la carta es sin gluten.`,
    skip: 'Ir al contenido',
    orgDesc: 'Grupo de restauración florentino con cuatro locales y obrador propio: toda la cocina es sin gluten.',
    cuisine: ['Toscana', 'Italiana'],
    menuName: 'Toda la carta, sin gluten',
  },
  nav: {
    home: 'Trattoria Boboli, inicio',
    book: 'Reservar',
    open: 'Abrir el menú',
    close: 'Cerrar el menú',
    menu: 'Carta',
    menuMeta: 'Todo sin gluten',
    lab: 'El obrador',
    labMeta: 'Hecho por nosotros',
    tagline: '100% sin gluten · desde 1978 · Florencia',
  },
  hero: {
    word: 'Elige',
    h1Hidden: 'cocina 100% sin gluten en Florencia',
    choices: ['la pasta.', 'el bocadillo.', 'comida o cena.', 'dónde sentarte.', 'con quién venir.', 'cómo vivir Boboli.'],
    choicesLabel: 'Lo que eliges en Boboli',
    answer: 'Todo sin gluten.',
    since: 'Florencia, desde 1978.',
    alt: 'Una cocinera de Boboli estira a mano pasta fresca sin gluten en el obrador',
  },
  choices: {
    title: 'En Boboli también eliges cómo disfrutar de la mesa.',
    homeVerb: 'Llévate Boboli a casa',
    homeWhere: 'Los productos del obrador',
    homeSub: 'Esas ganas de Boboli pueden seguir incluso cuando ya has vuelto a casa.',
  },
  format: { more: 'El local' },
  manifesto: {
    kicker: '100% sin gluten',
    title: 'Elige lo que te apetece comer.',
    body: 'Un plato de pasta humeante. Un bocadillo recién hecho. Un postre para compartir. El pan en el centro de la mesa. En Boboli todo es sin gluten, así que solo te queda elegir lo que de verdad te apetece.',
    items: ['Pasta', 'Pan', 'Bocadillos', 'Salsas', 'Postres', 'Carne'],
    listLabel: 'Lo que encuentras en la mesa',
  },
  lab: {
    kicker: 'El obrador',
    title: 'Hecho por nosotros.',
    thin: 'El pan lo hacemos nosotros. La pasta la hacemos nosotros. Y lo que va dentro también sale de nuestra cocina.',
    text: [
      'Porque hacer las cosas en casa no es solo una cuestión de tradición: es la forma que hemos elegido para saber exactamente qué llega a tu plato.',
      'Cada día partimos de ingredientes elegidos con cuidado y de recetas que conocemos bien. Así podemos llevar a la mesa una cocina sin gluten que no necesita imitar nada.',
    ],
    alt: 'El obrador de Boboli: pasta fresca hecha a mano',
  },
  menu: {
    title: 'Y tú, ¿qué te apetece comer hoy?',
    items: ['Pan', 'Bocadillos', 'Pasta fresca', 'Pasta', 'Salsas', 'Carne', 'Postres'],
    note: 'La elección es tuya. Nosotros nos encargamos de prepararla sin gluten.',
    gallery: {
      antipasti: ['Entrantes', 'Para poner en el centro y compartir.', 'Tabla toscana con bruschettas, embutidos, aceitunas y queso, todo sin gluten'],
      pasta: ['Pasta', 'La que te gustaría encontrar en el plato.', 'Tagliatelle al ragù sin gluten, hechas en el obrador de Boboli'],
      carne: ['Carne', 'Para cuando tienes hambre de verdad.', 'Bistecca alla fiorentina con una copa de vino tinto'],
      dolci: ['Postres', 'Para terminar como se debe.', 'Tiramisú sin gluten de Boboli'],
    },
    shopStrong: 'Llévate Boboli a casa.',
    shopText: 'La pasta, las salsas y el pan del obrador se venden en los locales. La tienda online está en camino.',
  },
  locations: {
    title: 'Cuatro direcciones, una sola forma de hacer Boboli.',
    sub: 'De la trattoria a la cantina, del bocadillo para llevar a la cena en el Bargello: elige el sitio que va contigo.',
    mapLabel: 'Mapa de los cuatro locales Boboli en Florencia',
    directions: 'Cómo llegar',
    landmarks: { duomo: 'Duomo', ponte: 'Ponte Vecchio', pitti: 'Palacio Pitti', boboli: 'Jardín de Bóboli', croce: 'Santa Croce' },
    firenzeCaption: 'Boboli es Florencia. Y Florencia también se come así.',
    firenzeAlt: 'Florencia vista desde el Jardín de Bóboli: el Duomo y los tejados de la ciudad',
  },
  seo: {
    title: 'Boboli en Florencia: cocina 100% sin gluten desde 1978',
    copy: (a) => [
      'Desde 1978 Boboli trae a Florencia una cocina pensada para compartir, elegir y disfrutar sin concesiones.',
      `Hoy nos encuentras en Via Romana y en Via Ghibellina, para ${a('al-bargello', 'una cena')}, ${a('trattoria-1978', 'una comida en la trattoria')}, ${a('la-cantina', 'una copa en la cantina')}, ${a('to-go', 'un bocadillo para llevar')} o ${a('prodotti', 'algo rico para llevarte a casa')}.`,
      'Nuestra cocina es 100% sin gluten, pero no es eso lo que queremos que recuerdes. Queremos que recuerdes lo que comiste, con quién estabas y cuánto disfrutaste el momento.',
    ],
    faqTitle: 'Preguntas frecuentes',
    faq: [
      ['¿Toda la carta es sin gluten?', 'Sí, en los cuatro locales. El sin gluten es el punto de partida de la cocina: pasta, pan, bocadillos, salsas y postres nacen en nuestro obrador.'],
      ['¿Dónde comer sin gluten en Florencia?', 'En el Oltrarno, en la Trattoria de Via Romana 45/R, en Boboli To-Go en el 52 y en la Cantina en el 60R; en Santa Croce, en el Bargello, Via Ghibellina 147/r.'],
      ['¿Hace falta reservar?', 'Es recomendable, sobre todo para cenar y los fines de semana. La Trattoria, el Bargello y la Cantina se reservan online con el botón Reservar; también puedes llamar a cualquier local.'],
      ['¿Tenéis comida para llevar y productos para casa?', 'Sí: Boboli To-Go en Via Romana 52 es nuestro local para llevar, y los productos del obrador — pasta, salsas, pan — se venden en los locales.'],
    ],
    hoursQ: '¿Qué horarios tienen los locales?',
  },
  book: {
    title: '¿Dónde quieres reservar?',
    sub: 'Cuatro locales, toda la carta sin gluten en cada uno.',
    book: 'Reservar',
    call: 'Llamar',
    back: 'Todos los locales',
    close: 'Cerrar',
    widget: (name) => `Reservar en ${name}`,
  },
  footer: {
    tagline: ['La libertad de elegir.', '100% sin gluten · Florencia, desde 1978'],
    locali: 'Los locales',
    discover: 'Descubre',
    links: { lab: 'El obrador', manifesto: '100% sin gluten', menu: 'La carta', shop: 'Los productos' },
    contact: 'Contacto',
    faq: 'Preguntas frecuentes',
  },
  place: {
    crumb: 'Ruta de navegación',
    address: 'Dirección',
    phone: 'Teléfono',
    hours: 'Horario',
    cuisine: 'Cocina',
    cuisineValue: 'Toscana, 100% sin gluten',
    directions: 'Cómo llegar',
    text: 'Toda la carta es sin gluten: pasta, pan, bocadillos, salsas y postres llegan de nuestro obrador.',
    others: 'Los otros locales',
  },
  hours: {
    short: { Mo: 'Lun', Tu: 'Mar', We: 'Mié', Th: 'Jue', Fr: 'Vie', Sa: 'Sáb', Su: 'Dom' },
    long: { Mo: 'lunes', Tu: 'martes', We: 'miércoles', Th: 'jueves', Fr: 'viernes', Sa: 'sábado', Su: 'domingo' },
    everyday: 'Todos los días',
    closed: (days) => `Cerrado los ${days}`,
    time: full,
  },
};

const de: Dict = {
  meta: {
    homeTitle: 'Boboli — Glutenfreie Restaurants in Florenz seit 1978',
    homeDesc:
      'Boboli in Florenz: vier Restaurants und eine eigene Manufaktur, die ganze Küche 100 % glutenfrei. Trattoria, Bargello, To-Go und Cantina in der Via Romana und Via Ghibellina. Online reservieren.',
    placeTitle: (name, street) => `${name} — glutenfreies Restaurant in Florenz · ${street}`,
    placeDesc: (legal, blurb, addr, zone) => `${legal}: ${blurb} ${addr}, ${zone}, Florenz. Die ganze Karte ist glutenfrei.`,
    skip: 'Zum Inhalt',
    orgDesc: 'Florentiner Gastronomiegruppe mit vier Restaurants und eigener Manufaktur: die ganze Küche ist glutenfrei.',
    cuisine: ['Toskanisch', 'Italienisch'],
    menuName: 'Die ganze Karte, glutenfrei',
  },
  nav: {
    home: 'Trattoria Boboli, Startseite',
    book: 'Reservieren',
    open: 'Menü öffnen',
    close: 'Menü schließen',
    menu: 'Speisekarte',
    menuMeta: 'Alles glutenfrei',
    lab: 'Die Manufaktur',
    labMeta: 'Von uns gemacht',
    tagline: '100 % glutenfrei · seit 1978 · Florenz',
  },
  hero: {
    word: 'Wähle',
    h1Hidden: '100 % glutenfreie Küche in Florenz',
    choices: ['die Pasta.', 'das Panino.', 'Mittag oder Abend.', 'deinen Platz.', 'deine Begleitung.', 'wie du Boboli erlebst.'],
    choicesLabel: 'Was du bei Boboli wählst',
    answer: 'Alles glutenfrei.',
    since: 'Florenz, seit 1978.',
    alt: 'Eine Köchin von Boboli rollt in der Manufaktur frische glutenfreie Pasta von Hand aus',
  },
  choices: {
    title: 'Bei Boboli wählst du auch, wie du genießt.',
    homeVerb: 'Nimm Boboli mit nach Hause',
    homeWhere: 'Produkte aus der Manufaktur',
    homeSub: 'Die Lust auf Boboli darf weitergehen, auch wenn du schon wieder zu Hause bist.',
  },
  format: { more: 'Das Restaurant' },
  manifesto: {
    kicker: '100 % glutenfrei',
    title: 'Wähle, worauf du Lust hast.',
    body: 'Dampfende Pasta. Ein frisch gemachtes Panino. Ein Dessert zum Teilen. Brot für die Mitte des Tisches. Bei Boboli ist alles glutenfrei, also bleibt nur zu wählen, worauf du wirklich Lust hast.',
    items: ['Pasta', 'Brot', 'Panini', 'Saucen', 'Desserts', 'Fleisch'],
    listLabel: 'Was auf den Tisch kommt',
  },
  lab: {
    kicker: 'Die Manufaktur',
    title: 'Von uns gemacht.',
    thin: 'Das Brot machen wir selbst. Die Pasta machen wir selbst. Und auch, was hineinkommt, entsteht in unserer Küche.',
    text: [
      'Denn selbst zu machen ist nicht nur eine Frage der Tradition: So wissen wir genau, was auf deinem Teller landet.',
      'Jeden Tag beginnen wir mit sorgfältig ausgewählten Zutaten und Rezepten, die wir gut kennen. So bringen wir eine glutenfreie Küche auf den Tisch, die nichts nachahmen muss.',
    ],
    alt: 'Die Manufaktur von Boboli: frische Pasta von Hand gemacht',
  },
  menu: {
    title: 'Und du, worauf hast du heute Lust?',
    items: ['Brot', 'Panini', 'Frische Pasta', 'Pasta', 'Saucen', 'Fleisch', 'Desserts'],
    note: 'Du wählst. Wir bereiten es glutenfrei zu.',
    gallery: {
      antipasti: ['Antipasti', 'Für die Mitte des Tisches, zum Teilen.', 'Toskanisches Brett mit Bruschetta, Wurst, Oliven und Käse, alles glutenfrei'],
      pasta: ['Pasta', 'So, wie du sie dir auf dem Teller wünschst.', 'Glutenfreie Tagliatelle mit Ragù aus der Boboli-Manufaktur'],
      carne: ['Fleisch', 'Für den richtig großen Hunger.', 'Bistecca alla fiorentina mit einem Glas Rotwein'],
      dolci: ['Desserts', 'Ein Abschluss, wie er sein soll.', 'Glutenfreies Tiramisù von Boboli'],
    },
    shopStrong: 'Nimm Boboli mit nach Hause.',
    shopText: 'Pasta, Saucen und Brot aus der Manufaktur gibt es in unseren Restaurants. Der Onlineshop kommt bald.',
  },
  locations: {
    title: 'Vier Adressen, eine Handschrift: Boboli.',
    sub: 'Von der Trattoria bis zur Cantina, vom Panino zum Mitnehmen bis zum Abendessen im Bargello: Wähle den Ort, der zu dir passt.',
    mapLabel: 'Karte der vier Boboli-Restaurants in Florenz',
    directions: 'Route',
    landmarks: { duomo: 'Dom', ponte: 'Ponte Vecchio', pitti: 'Palazzo Pitti', boboli: 'Boboli-Garten', croce: 'Santa Croce' },
    firenzeCaption: 'Boboli ist Florenz. Und so schmeckt Florenz auch.',
    firenzeAlt: 'Florenz vom Boboli-Garten aus: der Dom und die Dächer der Stadt',
  },
  seo: {
    title: 'Boboli in Florenz: 100 % glutenfreie Küche seit 1978',
    copy: (a) => [
      'Seit 1978 bringt Boboli eine Küche nach Florenz, die gemacht ist, um geteilt, gewählt und ohne Kompromisse genossen zu werden.',
      `Heute findest du uns in der Via Romana und in der Via Ghibellina: für ${a('al-bargello', 'ein Abendessen')}, ${a('trattoria-1978', 'ein Mittagessen in der Trattoria')}, ${a('la-cantina', 'ein Glas in der Cantina')}, ${a('to-go', 'ein Panino zum Mitnehmen')} oder ${a('prodotti', 'etwas Gutes für zu Hause')}.`,
      'Unsere Küche ist 100 % glutenfrei, aber das ist nicht das, woran du dich erinnern sollst. Wir wollen, dass du dich daran erinnerst, was du gegessen hast, mit wem du da warst und wie sehr du den Moment genossen hast.',
    ],
    faqTitle: 'Häufige Fragen',
    faq: [
      ['Ist die ganze Karte glutenfrei?', 'Ja, in allen vier Restaurants. Glutenfrei ist der Ausgangspunkt unserer Küche: Pasta, Brot, Panini, Saucen und Desserts entstehen in unserer eigenen Manufaktur.'],
      ['Wo kann man in Florenz glutenfrei essen?', 'Im Oltrarno in der Trattoria in der Via Romana 45/R, bei Boboli To-Go in Nr. 52 und in der Cantina in Nr. 60R; in Santa Croce im Bargello, Via Ghibellina 147/r.'],
      ['Muss ich reservieren?', 'Empfehlenswert, vor allem abends und am Wochenende. Trattoria, Bargello und Cantina reservierst du online über den Button Reservieren; jedes Restaurant ist auch telefonisch erreichbar.'],
      ['Gibt es Essen zum Mitnehmen und Produkte für zu Hause?', 'Ja: Boboli To-Go in der Via Romana 52 ist unser Take-away, und die Produkte der Manufaktur — Pasta, Saucen, Brot — gibt es in den Restaurants.'],
    ],
    hoursQ: 'Wann haben die Restaurants geöffnet?',
  },
  book: {
    title: 'Wo möchtest du reservieren?',
    sub: 'Vier Restaurants, in jedem die ganze Karte glutenfrei.',
    book: 'Reservieren',
    call: 'Anrufen',
    back: 'Alle Restaurants',
    close: 'Schließen',
    widget: (name) => `Reservieren bei ${name}`,
  },
  footer: {
    tagline: ['Die Freiheit zu wählen.', '100 % glutenfrei · Florenz, seit 1978'],
    locali: 'Unsere Restaurants',
    discover: 'Entdecken',
    links: { lab: 'Die Manufaktur', manifesto: '100 % glutenfrei', menu: 'Die Speisekarte', shop: 'Produkte' },
    contact: 'Kontakt',
    faq: 'Häufige Fragen',
  },
  place: {
    crumb: 'Navigationspfad',
    address: 'Adresse',
    phone: 'Telefon',
    hours: 'Öffnungszeiten',
    cuisine: 'Küche',
    cuisineValue: 'Toskanisch, 100 % glutenfrei',
    directions: 'Route planen',
    text: 'Die ganze Karte ist glutenfrei: Pasta, Brot, Panini, Saucen und Desserts kommen aus unserer eigenen Manufaktur.',
    others: 'Unsere anderen Restaurants',
  },
  hours: {
    short: { Mo: 'Mo', Tu: 'Di', We: 'Mi', Th: 'Do', Fr: 'Fr', Sa: 'Sa', Su: 'So' },
    long: { Mo: 'Montag', Tu: 'Dienstag', We: 'Mittwoch', Th: 'Donnerstag', Fr: 'Freitag', Sa: 'Samstag', Su: 'Sonntag' },
    everyday: 'Täglich',
    closed: (days) => `${days} geschlossen`,
    time: full,
  },
};

const fr: Dict = {
  meta: {
    homeTitle: 'Boboli — Restaurants sans gluten à Florence depuis 1978',
    homeDesc:
      'Boboli à Florence : quatre adresses et notre propre atelier, toute la cuisine 100 % sans gluten. Trattoria, Bargello, To-Go et Cantina via Romana et via Ghibellina. Réservation en ligne.',
    placeTitle: (name, street) => `${name} — restaurant sans gluten à Florence · ${street}`,
    placeDesc: (legal, blurb, addr, zone) => `${legal} : ${blurb} ${addr}, ${zone}, Florence. Toute la carte est sans gluten.`,
    skip: 'Aller au contenu',
    orgDesc: 'Groupe de restauration florentin avec quatre adresses et son propre atelier de production : toute la cuisine est sans gluten.',
    cuisine: ['Toscane', 'Italienne'],
    menuName: 'Toute la carte, sans gluten',
  },
  nav: {
    home: 'Trattoria Boboli, accueil',
    book: 'Réserver',
    open: 'Ouvrir le menu',
    close: 'Fermer le menu',
    menu: 'La carte',
    menuMeta: 'Tout sans gluten',
    lab: "L'atelier",
    labMeta: 'Fait maison',
    tagline: '100 % sans gluten · depuis 1978 · Florence',
  },
  hero: {
    word: 'Choisis',
    h1Hidden: 'une cuisine 100 % sans gluten à Florence',
    choices: ['les pâtes.', 'le sandwich.', 'déjeuner ou dîner.', 'où t’asseoir.', 'avec qui venir.', 'comment vivre Boboli.'],
    choicesLabel: 'Ce que tu choisis chez Boboli',
    answer: 'Tout sans gluten.',
    since: 'Florence, depuis 1978.',
    alt: "Une cuisinière de Boboli étale à la main des pâtes fraîches sans gluten dans l'atelier",
  },
  choices: {
    title: 'Chez Boboli, tu choisis aussi comment passer à table.',
    homeVerb: 'Emporte Boboli chez toi',
    homeWhere: "Les produits de l'atelier",
    homeSub: "L'envie de Boboli peut continuer même une fois rentré chez toi.",
  },
  format: { more: "L'adresse" },
  manifesto: {
    kicker: '100 % sans gluten',
    title: 'Choisis ce que tu as envie de manger.',
    body: "Des pâtes fumantes. Un sandwich tout juste préparé. Un dessert à partager. Le pain à poser au milieu de la table. Chez Boboli, tout est sans gluten : il ne reste plus qu'à choisir ce qui te fait vraiment envie.",
    items: ['Pâtes', 'Pain', 'Sandwichs', 'Sauces', 'Desserts', 'Viande'],
    listLabel: "Ce que tu trouves à table",
  },
  lab: {
    kicker: "L'atelier",
    title: 'Fait maison.',
    thin: "Le pain, on le fait nous-mêmes. Les pâtes, on les fait nous-mêmes. Et ce qu'on met dedans vient aussi de notre cuisine.",
    text: [
      "Parce que faire maison n'est pas qu'une question de tradition : c'est la façon que nous avons choisie pour savoir exactement ce qui arrive dans ton assiette.",
      "Chaque jour, nous partons d'ingrédients choisis avec soin et de recettes que nous connaissons bien. C'est ainsi que nous servons une cuisine sans gluten qui n'a besoin de rien imiter.",
    ],
    alt: "L'atelier de Boboli : des pâtes fraîches faites à la main",
  },
  menu: {
    title: "Et toi, qu'est-ce qui te fait envie aujourd'hui ?",
    items: ['Pain', 'Sandwichs', 'Pâtes fraîches', 'Pâtes', 'Sauces', 'Viande', 'Desserts'],
    note: "Le choix t'appartient. Nous nous occupons de le préparer sans gluten.",
    gallery: {
      antipasti: ['Antipasti', 'À poser au milieu et à partager.', 'Planche toscane avec bruschettas, charcuterie, olives et fromage, tout sans gluten'],
      pasta: ['Pâtes', 'Celles que tu aimerais trouver dans ton assiette.', "Tagliatelles au ragù sans gluten, faites à l'atelier Boboli"],
      carne: ['Viande', 'Pour quand tu as vraiment faim.', "Bistecca alla fiorentina avec un verre de vin rouge"],
      dolci: ['Desserts', 'Pour finir comme il se doit.', 'Tiramisù sans gluten de Boboli'],
    },
    shopStrong: 'Emporte Boboli chez toi.',
    shopText: "Pâtes, sauces et pain de l'atelier sont en vente dans nos adresses. La boutique en ligne arrive.",
  },
  locations: {
    title: 'Quatre adresses, un seul esprit Boboli.',
    sub: "De la trattoria à la cantina, du sandwich à emporter au dîner au Bargello : choisis l'endroit qui te ressemble.",
    mapLabel: 'Carte des quatre adresses Boboli à Florence',
    directions: 'Itinéraire',
    landmarks: { duomo: 'Duomo', ponte: 'Ponte Vecchio', pitti: 'Palais Pitti', boboli: 'Jardin de Boboli', croce: 'Santa Croce' },
    firenzeCaption: "Boboli, c'est Florence. Et Florence se mange aussi comme ça.",
    firenzeAlt: 'Florence vue du jardin de Boboli : le Duomo et les toits de la ville',
  },
  seo: {
    title: 'Boboli à Florence : cuisine 100 % sans gluten depuis 1978',
    copy: (a) => [
      'Depuis 1978, Boboli offre à Florence une cuisine pensée pour être partagée, choisie et savourée sans compromis.',
      `Aujourd'hui, tu nous trouves via Romana et via Ghibellina, pour ${a('al-bargello', 'un dîner')}, ${a('trattoria-1978', 'un déjeuner à la trattoria')}, ${a('la-cantina', 'un verre à la cantina')}, ${a('to-go', 'un sandwich à emporter')} ou ${a('prodotti', 'quelque chose de bon à rapporter chez toi')}.`,
      "Notre cuisine est 100 % sans gluten, mais ce n'est pas ce que nous voulons que tu retiennes. Nous voulons que tu te souviennes de ce que tu as mangé, de qui était avec toi et du plaisir que tu as pris.",
    ],
    faqTitle: 'Questions fréquentes',
    faq: [
      ['Toute la carte est-elle sans gluten ?', "Oui, dans nos quatre adresses. Le sans gluten est le point de départ de notre cuisine : pâtes, pain, sandwichs, sauces et desserts naissent dans notre atelier."],
      ['Où manger sans gluten à Florence ?', "Dans l'Oltrarno, à la Trattoria au 45/R de la via Romana, chez Boboli To-Go au 52 et à la Cantina au 60R ; à Santa Croce, au Bargello, via Ghibellina 147/r."],
      ['Faut-il réserver ?', "C'est conseillé, surtout le soir et le week-end. La Trattoria, le Bargello et la Cantina se réservent en ligne avec le bouton Réserver ; chaque adresse répond aussi au téléphone."],
      ['Faites-vous de la vente à emporter et des produits à rapporter ?', "Oui : Boboli To-Go, au 52 de la via Romana, est notre adresse à emporter, et les produits de l'atelier — pâtes, sauces, pain — sont en vente dans nos adresses."],
    ],
    hoursQ: "Quels sont les horaires d'ouverture ?",
  },
  book: {
    title: 'Où veux-tu réserver ?',
    sub: 'Quatre adresses, toute la carte sans gluten dans chacune.',
    book: 'Réserver',
    call: 'Appeler',
    back: 'Toutes les adresses',
    close: 'Fermer',
    widget: (name) => `Réserver chez ${name}`,
  },
  footer: {
    tagline: ['La liberté de choisir.', '100 % sans gluten · Florence, depuis 1978'],
    locali: 'Nos adresses',
    discover: 'Découvrir',
    links: { lab: "L'atelier", manifesto: '100 % sans gluten', menu: 'La carte', shop: 'Les produits' },
    contact: 'Contact',
    faq: 'Questions fréquentes',
  },
  place: {
    crumb: "Fil d'Ariane",
    address: 'Adresse',
    phone: 'Téléphone',
    hours: 'Horaires',
    cuisine: 'Cuisine',
    cuisineValue: 'Toscane, 100 % sans gluten',
    directions: 'Itinéraire',
    text: "Toute la carte est sans gluten : pâtes, pain, sandwichs, sauces et desserts viennent de notre atelier.",
    others: 'Nos autres adresses',
  },
  hours: {
    short: { Mo: 'Lun', Tu: 'Mar', We: 'Mer', Th: 'Jeu', Fr: 'Ven', Sa: 'Sam', Su: 'Dim' },
    long: { Mo: 'lundi', Tu: 'mardi', We: 'mercredi', Th: 'jeudi', Fr: 'vendredi', Sa: 'samedi', Su: 'dimanche' },
    everyday: 'Tous les jours',
    closed: (days) => `Fermé le ${days}`,
    time: (t) => t.replace(/^0/, '').replace(':', 'h').replace(/h00$/, 'h'),
  },
};

export const ui: Record<Lang, Dict> = { it, en, es, de, fr };
